# .github/workflows/is-version-bump.yml
# Reusable workflow: checks if the triggering commit is a version bump.
#
# Returns is_version_bump=true when the head commit message starts with
# 'chore: bump version'. Pure shell — no dependency on git-semver script.

name: Is Version Bump

on:
  workflow_call:
    outputs:
      is_version_bump:
        description: "Whether this is a version bump commit"
        value: ${{ jobs.check.outputs.result }}

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.check.outputs.result }}
    steps:
      - name: Check commit message
        id: check
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          if [[ "$COMMIT_MSG" == "chore: bump version"* ]]; then
            echo "result=true" >> $GITHUB_OUTPUT
            echo "Version bump commit detected"
          else
            echo "result=false" >> $GITHUB_OUTPUT
            echo "Not a version bump commit"
          fi
