# .github/workflows/release.yml
# Creates a GitHub Release when a version tag is pushed.
#
# Triggered by version-bump.yml which creates and pushes v* tags.
# Supports both root tags (v1.0.0) and subdirectory tags (frontend/v1.0.0).

name: Release

on:
  push:
    tags:
      - 'v*'
      - '*/v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "${{ github.ref_name }}" \
            --repo "${{ github.repository }}" \
            --title "${{ github.ref_name }}" \
            --generate-notes
